### ISSUE TITLE
Grouping by third attribute fails in bar chart.

### ISSUE THREAD

**Issue by moosilauke18** [rstudio/ggvis#164]
I have bar chart I'm trying to transfer from ggplot2 to ggvis to add interactivity.  My original chart 

```
Plot_Data %>%
    ggvis(x = ~month, y = ~count) %>%
    group_by(~Product) %>%
    layer_bars()
```

This is what the original graph looks like:
![image](https://cloud.githubusercontent.com/assets/1585809/3085962/aa0fb7a4-e51f-11e3-9a24-1af25cf899d3.png)

**Comment by voxnonecho** [comment]
@wch Is this still on the roadmap ?

**Comment by holstius** [comment]
+1. Are there milestone(s) for "dodged and stacked" bars?

**Comment by emschuch** [comment]
A little sad that this conversation is so old and it hasn't been incorporated yet. I really wanted to make a grouped horizontal bar chart, so I came up with a somewhat hacky solution.

The code in my shiny app looks like this:
```
bar <- data %>% 
        ggvis(y = ~factor(y_var, levels = sort_order), stroke := "#none", fill = ~fill_var) %>%
        group_by(fill_var) %>%
        layer_rects(x = 0, x2 = ~x_var, height = band()) %>%
        scale_nominal("y", padding = 0.6, points = FALSE) %>%
        add_tooltip(bar_tooltip, "hover") %>%
        set_options(width = 1150, height = 500) %>%
        bind_shiny('bar')
```
That will layer the rects on top of each other. To offset them, I inspected in the developer tools to find the group id for each bar group, then added the following to my css code:
```
#g39 {
	transform: translate(0, 7.5px);
}
#g40 {
	transform: translate(0, -7.5px);
}
```
In the R viewer the bars are still overlapping, but opening in a browser, the results look like this:
![bar](https://cloud.githubusercontent.com/assets/6503209/14110308/dbc1f90c-f593-11e5-8ada-c070b87e4160.PNG)

**Comment by drcrook1** [comment]
I need this in a big way.  This is blocking adoption at several large clients.
