### ISSUE TITLE
group_by should understand reactives

### ISSUE THREAD

**Issue by wch** [rstudio/ggvis#212]
Example:

``` R
library(shiny)
library(ggvis)

# OK
mtcars %>% group_by(cyl) %>% ggvis(~wt, ~mpg)


mtc <- reactive(mtcars)
# Not OK
mtc %>% group_by(cyl) %>% ggvis(~wt, ~mpg)
# Error in UseMethod("regroup") : 
#  no applicable method for 'regroup' applied to an object of class "reactive" 
```

Not sure if this should be considered a ggvis or dplyr issue.

**Comment by joseramoncajide** [comment]
`dataset <- reactive(dataset)

customer_interactions <-  dataset %>%  group_by(item_id) %>% arrange(item_id) %>% distinct(item_name, .keep_all = TRUE)   %>%  group_by(item_id)  %>% summarise(n = n()) %>% arrange(desc(n)) 

`

`Error in UseMethod("group_by_") : 
  no applicable method for 'group_by_' applied to an object of class "reactive"`

Can I use group_by into a reactive environment?

**Comment by bborgesr** [comment]
@joseramoncajide, can you give a reproducible example?

I think `group_by` works just fine with reactives since Winston's example is fine:

```r
mtc <- reactive(mtcars)
mtc %>% group_by(cyl) %>% ggvis(~wt, ~mpg)
```
