### ISSUE TITLE
Can't hide legend for tiles

### ISSUE THREAD

**Issue by kismsu** [rstudio/ggvis#218]
Hi, I've tried to modify your heat map example but without legend, but hide_legend doesn't work

hec <- as.data.frame(xtabs(Freq ~ Hair + Eye, HairEyeColor))
hec %>% 
    ggvis(~Hair, ~Eye, fill = ~Freq) %>% 
    layer_rects(width = band(), height = band()) %>%
    scale_nominal("x", padding = 0, points = FALSE) %>%
    scale_nominal("y", padding = 0, points = FALSE) %>%
    hide_legend("fill")

**Comment by Lwan12** [comment]
> Hi, I've tried to modify your heat map example but without legend, but hide_legend doesn't work
> 
> hec <- as.data.frame(xtabs(Freq ~ Hair + Eye, HairEyeColor))
> hec %>%
> ggvis(~Hair, ~Eye, fill = ~Freq) %>%
> layer_rects(width = band(), height = band()) %>%
> scale_nominal("x", padding = 0, points = FALSE) %>%
> scale_nominal("y", padding = 0, points = FALSE) %>%
> hide_legend("fill")

Did you find the correct code to hide it？
