### ISSUE TITLE
hide_legend does not actually hide the legend.

### ISSUE THREAD

**Issue by jimhester** [rstudio/ggvis#229]
ggvis_0.3.0.1 from CRAN

The example from the hide_legend help still displays a legend.

```
mtcars %>% ggvis(x = ~wt, y=~mpg, fill = ~cyl) %>% layer_points() %>% hide_legend('fill')
```

**Comment by mtelesha** [comment]
It is still not fixed after installing from devtools.

4.2.9000

  data %>% 
  summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
  gather(na.rm = TRUE) %>% 
  ggvis(x = ~key, y = ~value) %>%
  layer_paths(stroke = "blue", strokeWidth := 5) %>%
  layer_points(fill = "blue", strokeWidth := 10) %>%
  hide_legend("fill")
