### ISSUE TITLE
qvis() is not working with the latest ?

### ISSUE THREAD

**Issue by kanaugust** [rstudio/ggvis#245]
Version: 0.3.0.1

> devtools::install_github("rstudio/ggvis", build_vignettes = FALSE)
> library(ggvis)
> qvis(mtcars, ~wt, ~mpg)

Error: could not find function "qvis"

Is this still supported ?

**Comment by joliverson** [comment]
Can someone please update the tutorial on http://ggvis.rstudio.com/0.1/ggvis-basics.html.

Thanks

**Comment by ellisp** [comment]
@joliverson that site is very old (I wonder why RStudio keeps it up, as it traps a lot of people via google) and is superseded by http://ggvis.rstudio.com/ which has all the latest functionality and examples.
