### ISSUE TITLE
Check box problems

### ISSUE THREAD

**Issue by hadley** [rstudio/ggvis#272]
``` R
cocaine %>%  
  ggvis(~potency, ~price) %>%
  filter(state %in% eval(input_checkboxgroup(c("IA", "MN", "WI")))) %>%
  layer_points(fill = ~state, size := 50, opacity := 0.5)
```

This fails because there are no groups selected, and ggvis fails with an empty data frame. I think there are two fixes needed:
- [ ] `input_checkboxgroup()` should select all values by default (easy)
- [ ] any empty data frame should succeed (hard)

**Comment by sebastian-c** [comment]
I'm using the latest development version of `ggvis` and using the examples given in this issue gives:

```
Error in filter(., state %in% eval(input_checkboxgroup(choices, selected = choices))) : 
  (list) object cannot be coerced to type 'double'
```

**Comment by sosulski** [comment]
I'm getting the same error.

**Comment by sosulski** [comment]
I was able to solve it... This was my code... 

library(dplyr)    
library(ggvis)

bikeshare %>% 
  ggvis(x=~cnt, y=~atemp) %>% 
  filter(bikeshare$season %in% eval(input_checkboxgroup(choices=unique(bikeshare$season), 
    selected = "1")))%>% 
layer_points(fill = ~season)   %>% 
  add_axis("x", title = "Number of rentals per day") %>%
  add_axis("y", title = "Average daily temperature in degrees fahrenheit")
