### ISSUE TITLE
add_tooltip hyperlinks are inactive

### ISSUE THREAD

**Issue by AlunHewinson** [rstudio/ggvis#349]
A hyperlink created in add_tooltip does not work when clicked.
When clicking on a data point, the tooltip opens displaying the link.  But clicking the link produces no action.

The html appears to be well formed.  Is there an explanation, workaround or fix for this behaviour?

<pre>
library(ggvis)
iris %>%
    ggvis(~Sepal.Width, ~Petal.Length, shape=~Species) %>%
    layer_points() %>%
    add_tooltip(html=function(df) paste0('&lt;a href=',
                                         '"http://en.wikipedia.org/wiki/Iris_',
                                         df$Species, '"&gt;',
                                         df$Species, ' (wikipedia)&lt;/a&gt;'),
                on="click")
</pre>

**Comment by wch** [comment]
Looks like this was because we had `pointer-events: none` in the CSS for the tooltip. I can't think of why that would be useful, so I removed it.
