### ISSUE TITLE
activate dest parameter in view_static 

### ISSUE THREAD

**Issue by fak** [rstudio/ggvis#350]
In the current ggvis, `view_static` does not process the `dest` parameter. But this would be very useful, because this way users could direct the (static) html output directly to a target destination, otherwise need to find it among other tmp files. 

`view_static` is defined in [print.R](https://github.com/rstudio/ggvis/blob/2652f7e31f2b820e19de6258349cfef5bdb1405d/R/print.R).

This issue comes from a question on SO http://stackoverflow.com/questions/28093605/using-ggvis-view-static-to-export-html-file-and-dependencies

**Comment by wch** [comment]
Hm, it looks like that got lost in 84d2b76eae16c5cc2d0790788ac284a5bfc50885.

**Comment by wch** [comment]
I don't think it'll be possible to implement this unless changes are made to `htmltools::html_print`. But you can do this:

```R
outfile <- mtcars %>% ggvis(~wt, ~mpg) %>% view_static() %>% htmltools::html_print()
outfile
# [1] "/tmp/Rtmps5hgoi/viewhtml266b14fd08f8/index.html"
```

I'll update the documentation to reflect this.

**Comment by fak** [comment]
Thanks!

    outfile <- mtcars %>% ggvis(~wt, ~mpg) %>% view_static() %>% htmltools::html_print()

Should work for me.

**Comment by wch** [comment]
Great!
