### ISSUE TITLE
ggvis plots in Shiny app disappearing (flashing)

### ISSUE THREAD

**Issue by wch** [rstudio/ggvis#351]
(Moving this from rstudio/shiny#714. Content below was originally posted by @fereshtehRS.)

This issue was reported as a Shiny Server issue:

https://support.rstudio.com/hc/communities/public/questions/202231898-flashing-ggvis-graphs-on-shiny-server

I responded and have been going back and forth with the person. He provided with a small reproducible application (code below), deployed here:

https://fereshteh.shinyapps.io/markus-ggvis-app/

You can see the flashing more easily on Firefox and Safari. 

But the problem also happens when running the code locally, in a browser (not the viewer). So I don't think it is a server issue.

server.R
```
library(shiny)
library(ggvis)
library(dplyr)

server <- function(input, output, session) {
  
  # to deal correctly with milliseconds in timestamp
  options(digits=15)
  
  connectToStream <- reactive({
    
    invalidateLater(3000, session)
    
    data <- data.frame(sensorname = "screenAdjustedEvent",
                       x=1:10,y=runif(10, 5.0, 7.5),z=1:10, 
                       recordTime=as.numeric(Sys.time())-(1:10),
                       device="iPhone", cognitoId="abc",
                       ip="dddd")
    
    data
  })
  
  
  
  # Device Orientation
  devOrA <- reactive({
    streamdata <- connectToStream()
    
    out <- streamdata %>% 
      filter(sensorname == "screenAdjustedEvent") %>% 
      filter(recordTime > max(recordTime) - 30)  %>% 
      ggvis(x = ~recordTime, 
            y = ~x) 
    out
  })
  devOrA %>% bind_shiny("devOrA","devOrA_ui", session) 
  
  devOrB <- reactive({
    streamdata <- connectToStream()
    
    out <- streamdata %>% 
      filter(sensorname == "screenAdjustedEvent") %>% 
      filter(recordTime > max(recordTime) - 30)  %>%
      ggvis(x = ~recordTime, 
            y = ~y) 
    out
  })
  devOrB %>% bind_shiny("devOrB","devOrB_ui", session) 
  
  devOrG <- reactive({
    streamdata <- connectToStream()
    
    out <- streamdata %>% 
      filter(sensorname == "screenAdjustedEvent") %>% 
      filter(recordTime > max(recordTime) - 30)  %>% 
      ggvis(x = ~recordTime, 
            y = ~z) 
    out
  })
  devOrG %>% bind_shiny("devOrG","devOrG_ui", session) 
  
}
```

ui.R
```
library(shiny)
library(ggvis)

shinyUI(bootstrapPage(
  ggvisOutput("devOrA"),
  uiOutput("devOrA_ui"),
  ggvisOutput("devOrB"),
  uiOutput("devOrB_ui"),
  ggvisOutput("devOrG"),
  uiOutput("devOrG_ui")
  
)
)
```

**Comment by wch** [comment]
I'm not yet sure of the exact cause of bug yet. However, there is a better way of structuring the code so that the bug doesn't occur.

Instead of putting the `ggvis()` call inside each reactive, you can have each reactive return data, and feed the reactive into `ggvis()`, like so (this is written as a single-file app):

```R
library(shiny)
library(ggvis)
library(dplyr)

ui <- shinyUI(bootstrapPage(
  ggvisOutput("devOrA"),
  uiOutput("devOrA_ui"),
  ggvisOutput("devOrB"),
  uiOutput("devOrB_ui"),
  ggvisOutput("devOrG"),
  uiOutput("devOrG_ui")
))


server <- function(input, output, session) {

  # to deal correctly with milliseconds in timestamp
  options(digits=15)

  connectToStream <- reactive({

    invalidateLater(3000, session)

    data <- data.frame(sensorname = "screenAdjustedEvent",
                       x=1:10,y=runif(10, 5.0, 7.5),z=1:10,
                       recordTime=as.numeric(Sys.time())-(1:10),
                       device="iPhone", cognitoId="abc",
                       ip="dddd")
    data
  })

  # Device Orientation
  devOrA <- reactive({
    streamdata <- connectToStream()

    streamdata %>%
      filter(sensorname == "screenAdjustedEvent") %>%
      filter(recordTime > max(recordTime) - 30)
  })
  devOrA %>%
    ggvis(x = ~recordTime, y = ~x) %>%
    bind_shiny("devOrA","devOrA_ui", session)

  devOrB <- reactive({
    streamdata <- connectToStream()

    streamdata %>%
      filter(sensorname == "screenAdjustedEvent") %>%
      filter(recordTime > max(recordTime) - 30)
  })
  devOrB %>%
    ggvis(x = ~recordTime, y = ~x) %>%
    bind_shiny("devOrB", "devOrB_ui", session)

  devOrG <- reactive({
    streamdata <- connectToStream()

    streamdata %>%
      filter(sensorname == "screenAdjustedEvent") %>%
      filter(recordTime > max(recordTime) - 30)
  })
  devOrG %>%
    ggvis(x = ~recordTime, y = ~z) %>%
    bind_shiny("devOrG","devOrG_ui", session)
}


shinyApp(ui, server)
```

This structure also allows for smooth transitions, although it can be disabled with `set_options(duration=0)`.

**Comment by schmidb** [comment]
Thanks a lot.Your proposed solution is working.

**Comment by wch** [comment]
@schmidb I also just noticed that the `session` object passed to `bind_shiny` isn't in the correct position. Right now, it's being used as a `...` argument. But you can leave the `session` out of the `bind_shiny` call entirely because it's automatically detected.

With some console debugging, I've found that the callback functions are executed in different orders in Chrome vs. Firefox. There's a [`setTimeout`](https://github.com/trifacta/vega/blob/14054313910a3665941e5b4b845308d3f81b9fef/src/parse/data.js#L60) when Vega processes a spec, and I believe that's part of the issue.

Here's a smaller example:

```R
library(shiny)
library(ggvis)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      actionButton('go', 'Go!')
    ),
    mainPanel(
      ggvisOutput("plotA"),
      ggvisOutput("plotB")
    )
  )
)

server <- function(input, output, session) {
  dataSource <- reactive({
    input$go
    data.frame(x = 1:10, y = 1:10)
  })

  # Device Orientation
  plotA <- reactive({
    dataSource() %>%
      ggvis(x = ~x, y = ~y) %>%
      set_options(width=200, height=200)
  })
  plotA %>%
    bind_shiny("plotA")

  plotB <- reactive({
    dataSource() %>%
      ggvis(x = ~x, y = ~y) %>%
      set_options(width=200, height=200)
  })
  plotB %>%
    bind_shiny("plotB")
}

shinyApp(ui, server)
```

**Comment by vzemlys** [comment]
I've got bitten by this bug also, but did not know how to reproduce it. It seems that it is gone now. Note, that the code rearrangement solution was not possible for me. I have a quite elaborate ggvis graph, so I created a function which creates ggvis graph based on various arguments. So I need to pass not only the data, but also a bunch of other arguments, which I fold to a list. Now if I pass this list as a reactive expression to my function, I get the reactive instead of a list and I am not well versed in reactive coding to know what to do with it :)

**Comment by ejanalysis** [comment]
Also, why did @wch say this?

    plotA %>%
      bind_shiny("plotA")

instead of 

    observe( 
      plotA() %>%
        bind_shiny("plotA")
    )

How does a reactive like plotA behave if you say plotA instead of plotA() ? When is that useful or appropriate?

**Comment by ejanalysis** [comment]
Possibly a related bug/problem is still open here:
http://stackoverflow.com/questions/28915921/ggvis-plot-disappears-at-random-shiny/28987413#28987413

**Comment by colinrodriguez** [comment]
The disappearing plot issue still seems present to some extent in ggvis 0.4.2. Unfortunately I'm not clear on precise details. 

In case it helps anyone else that hits this page, my overkill workaround is to not try and update an existing plot, but rather toss out the old plot and create an entirely new one and then call bind_shiny using a different plot id. Not the most elegant and you lose some niceties but seemed to work for me.

Something like:

```r
library(shiny)
library(ggvis)
library(uuid)

ui <- fluidPage(
  # whatever controls you need
  uiOutput("plot1")
)

server <- function(input, output, session) {
  dataSource <- reactive({
    # do whatever is needed to generate reactive data...
  })

  output$plot1 <- renderUI({
    data <- dataSource()
   
    # use your preferred method to generate a new plot id not previously used!
    plotId <- paste0("plot1", UUIDgenerate(FALSE))
    data %>%
      ggvis(x = ~x, y = ~y) %>%
      bind_shiny(plotId)
    ggvisOutput(plotId) 
  })
}

shinyApp(ui, server)
```
