### ISSUE TITLE
Slider example from http://ggvis.rstudio.com/0.1/quick-examples.html produces an error

### ISSUE THREAD

**Issue by kendonB** [rstudio/ggvis#368]
When I try and run:
    
    library(ggvis)
    ggvis(mtcars, props(x = ~wt, y = ~mpg)) +
      layer_smooth(se = TRUE,
        span = input_slider(min = 0.3, max = 1, value = 0.8, step = 0.1,
          label = "Smoothing span")) +
      layer_point() +
      guide_axis("x", title = "Weight") +
      guide_axis("y", title = "MPG")

which is taken from http://ggvis.rstudio.com/0.1/quick-examples.html,

I get the following error:
    
    Error in new_prop.default(x, property, scale, offset, mult, env, event,  : 
    Unknown input to prop: list(property = "x", value = wt, scale = "x", offset = NULL, mult = NULL, event = "update", env = <environment>)list(property = "y", value = mpg, scale = "y", offset = NULL, mult = NULL, event = "update", env = <environment>)

I am on R 3.1.2 x64 Windows 8.1.

**Comment by wch** [comment]
That example is for an old, outdated version of ggvis. This is the current page:
http://ggvis.rstudio.com/cookbook.html

Where did you get that link from?

**Comment by kendonB** [comment]
I started looking at this on rstudio.com yesterday, but can't find where I got that link from. Very strange.

**Comment by wch** [comment]
Strange. Well, if you do come across it again, please let us know.

**Comment by taschmitt** [comment]
Got the same error. So this link is no longer valid then: http://ggvis.rstudio.com/0.1/quick-examples.html

**Comment by wch** [comment]
The link is valid, but it's for ggvis version 0.1. The current version is 0.4.1.

**Comment by devmacrile** [comment]
Winston,
That link is the top search hit for "ggvis example" since there is no longer a page with "example" in the name.  Just came across this.

Anyways, thanks.

**Comment by aeleuterio** [comment]
I also came across this broken example as the first search result; perhaps it would be a good idea to state clearly what version the test is for
