### ISSUE TITLE
ggvis plot disappears at random Shiny - possible bug in bind_shiny()

### ISSUE THREAD

**Issue by Nicolabo** [rstudio/ggvis#376]
I have a strange problem in Shiny. I published the same question in stackoverflow.com and one guy named `numbercruncher` claims it refers to some bug in `bind_shiny`.  My shiny app has one ggvis plot with layer_points() and several options to manipulate the plot . When I run my app sometimes everything works good even if I change all options, but sometimes ( I suppose there is no specific rule) plot disappers. Plot comes back when I change one of options but it is not cool. I study this issue but I do not really know whether it is a solution for my problem. When the plot disappears my Shiny app looks like:
![zrzut ekranu 2015-03-11 o 18 15 10](https://cloud.githubusercontent.com/assets/5960799/6602229/a134ee5e-c81a-11e4-80be-d5adbabbe38b.png)

Here you can find my code:
https://gist.github.com/Nicolabo/6b272cd9f1de9af8c81b

**Comment by vzemlys** [comment]
Which version of shiny and ggvis are you using? This seems like issue #351 which is fixed in development version of ggvis.

**Comment by Nicolabo** [comment]
I use `ggvis_0.4.0.9000`  and `shiny_0.10.2`

**Comment by Nicolabo** [comment]
Tkanks for answer for so silly question. Works correctly now.

**Comment by wch** [comment]
Great, glad it works. We're going to put out a new release of ggvis today or tomorrow, so it should soon work from the CRAN version as well.
