### ISSUE TITLE
multiple legends?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/ggvis#399]
Suppose my data looks like this:

    DF <- data.frame(x=as.factor(c("A","A", "B", "B")),
                     y=c(0.02, 0.016, 0.012, 0.008),
                     type = as.factor(c('d','f','d','f')),
                     se=c(0.023, 0.014, 0.011, 0.016))

I want to have two legends. One for the combination fill stroke and one for size.

This is the code I have right now

    DF %>% 
      ggvis(x = ~x, y = ~y, 
            stroke = ~type, strokeWidth := 2, 
            fill=~x, size=~se) %>% 
      layer_points() %>%
      add_legend(c("fill", "stroke"), 
                 title = "Something") %>%
      add_legend('size', title = "Another Legend")

How can I fix it?

Thanks!

**Comment by ignacio82** [comment]
Answer from [stackoverflow](http://stackoverflow.com/questions/29785281/ggvis-with-tooltip-not-working-with-layer-smooths/30359607#30359607)

		library(ggvis)
		mtc <- mtcars
		mtc$id <- seq_len(nrow(mtc))

		all_values <- function(x) 
		 {
		   if(is.null(x)) return(NULL)
		   row <- mtc[mtc$id == x$id, ]
		   paste0(names(row), ": ", format(row), collapse = "<br />")
		 }

		mtc %>% ggvis(x = ~wt, y = ~mpg) %>%
		  layer_smooths(stroke := "red", se = T) %>%
		  layer_points(key := ~id) %>%
		  add_tooltip(all_values, "hover")

However, when you hover over the smooth or the confidence bands, all of the values associated with the variables are labeled 'character(0)' in the tooltip.

**Comment by mbacou** [comment]
Same problem here. Multiple legends are positioned on top of one another.

**Comment by mbacou** [comment]
Sorry I see it's a dup of https://github.com/rstudio/ggvis/issues/347
