### ISSUE TITLE
add a title to a plot

### ISSUE THREAD

**Issue by Mullefa** [rstudio/ggvis#403]
Does ggvis currently support adding a title to a plot? 

Couldn't seem to find any official documentation on this - the most useful resource I found was [this](http://stackoverflow.com/questions/25018598/add-a-plot-title-to-ggvis) question on SO.

**Comment by daattali** [comment]
+1, I was just thinking the same thing and was just about to open an issue

**Comment by ellisp** [comment]
Duplicates #258

**Comment by pseemakurthi** [comment]
add_title() isn't working ?
