### ISSUE TITLE
Installing latest version

### ISSUE THREAD

**Issue by geoHeil** [rstudio/ggvis#407]
Hi, when I install

devtools::install_github("hadley/lazyeval")
devtools::install_github("hadley/dplyr")
devtools::install_github("rstudio/ggvis")

I get the following error for all of these:

Error in get(method, envir = home) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/ggvis/R/ggvis.rdb' is corrupt
Zusätzlich: Warning message:
In get(method, envir = home) : internal error -3 in R_decompress1

**Comment by vzemlys** [comment]
The packages were already loaded when you did the install. Restart R and the error message will go away.

**Comment by geoHeil** [comment]
Thanks.

**Comment by geoHeil** [comment]
But  still resizable plots like https://github.com/rstudio/ggvis/blob/master/man/set_options.Rd do not seem to work for me.
