### ISSUE TITLE
Treemaps?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/ggvis#411]
Is it possible to create an interactive treemap with ggvis? Right now, I can do it with googleVis:

    library(googleVis)
    Tree <- gvisTreeMap(Regions,  idvar="Region", parentvar="Parent",
                        sizevar="Val", colorvar="Fac")
    plot(Tree)

or with [treemapify](https://github.com/wilkox/treemapify)

Thanks!

**Comment by hadley** [comment]
Not at this time
