### ISSUE TITLE
basic example ggvis does not work in R3.6.3/4.0.0

### ISSUE THREAD

**Issue by aldojongejan** [rstudio/ggvis#483]
Dear all,
Allthough I realise ggvis is 'dormant' I still would like to report that for me the basic example 'mtcars %>% ggvis(~mpg, ~wt) %>% layer_points()'  does not work. My in-house Shiny-app use ggvis code to display volcanoplot to be interactively explored by researcher, but this also does not work any longer.
Attached is a screenshot for R4.0.0 (in RStudio v1.3.959), but it also holds for R3.6.3. At least in R3.5.1 it still worked...

Anybody any ideas, how to get it working again (and what causes it)?
regards,
Aldo
![R4 0 0 ggvis_problem](https://user-images.githubusercontent.com/16121209/84113283-97c77100-aa2a-11ea-8424-6587e039bb89.PNG)

**Comment by 3210sq** [comment]
I have the same problem。

**Comment by usamaa9** [comment]
The issue is being caused by the dependencies of ggvis namely:
shiny, use 1.4.0
dplyr, use 0.8.3
htmltools, use 0.4.0 

I've tested this on windows with R 3.6.3 and the basic example then gives the points. You will need Rtools (older version which will work with 3.6.3) and then install devtools package to then install the old versions of the package. Will post a complete solution once I have it all tested.

**Comment by opendatasurgeon** [comment]
Hello I am having similar issues on Windows 10. Looks like Linux is not affected by this. I have an up-to-date R studio there, but most likely the dependent packages are old, so I am seeing no issues. Let's hope we get an update soon :)

**Comment by usamaa9** [comment]
I have this issue on alpine 3.11.5 and 3.12

**Comment by aldojongejan** [comment]
It seems only dplyr needs to be downgraded to 0.8.3 on R4.0.0



ggvis_0.4.5

dplyr_0.8.3
shiny_1.4.0.2

htmltools_0.4.0

works as a charm!

**Comment by 3210sq** [comment]
Thx

**Comment by wilhem** [comment]
I have the same problem

Even downgrading shiny and dplyr to that versions, it doesn't work.

Do you have any idea?

**Comment by lionel-** [comment]
I'll take a quick look today, maybe it's something easy to fix.

**Comment by lionel-** [comment]
I have sent a PR, in the meantime you can install this branch to fix the problem:

```r
remotes::install_github("lionel-/ggvis@fix-dplyr-1-0-0")
```

**Comment by wilhem** [comment]
The fix:

`remotes::install_github("lionel-/ggvis@fix-dplyr-1-0-0")`

works!!!!

**Comment by wilhem** [comment]
I think, I was too soon happy....

I discovered that the fix above works for small datasets like `iris` for example, but it doesn't work for datasets like 
`diamonds`

**Comment by lionel-** [comment]
@wilhem Please post a reprex.

**Comment by wilhem** [comment]
Hi Lionel,

I try again with the diamonds dataset.

It works now. 
I don't know why. I just updated R two days ago. Every package.

Now it seems to work even for diamonds
Thanks!
