### ISSUE TITLE
remove lazyeval implementations for dplyr verbs

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/ggvis#487]
We're trying to remove the `*_()` verbs from `dplyr` : 

https://github.com/tidyverse/dplyr/issues/5573
https://github.com/tidyverse/dplyr/pull/5592

Initially we'd just like to remove the fallbacks that call the underscore function, and then later we'll remove the underscore function altogether. 

For example, we'd like to remove this:  

```r
group_by.default <- function(.data, ..., add = FALSE, .drop = group_by_drop_default(.data)) {		
   group_by_(.data, .dots = compat_as_lazy_dots(...), add = add)		
 }
```

but ggvis uses them, e.g.: https://github.com/rstudio/ggvis/blob/master/R/dplyr.R

```r
group_by_.ggvis <- function(.data, ..., .dots, add = FALSE) {
  dots <- lazyeval::all_dots(.dots, ...)
  pieces <- extract_lazy_inputs(dots)

  register_computation(.data, pieces$inputs, "group_by", function(data, args) {
    dplyr::group_by_(data, .dots = lapply(pieces$lazy, add_args, args),
      add = add)
  })
}
```

Perhaps `ggvis` could instead define methods for the non underscore verbs instead ?

**Comment by wch** [comment]
I don't have time to implement that, but I'd be happy to look at a PR. We'll probably have to keep the underscore functions in ggvis for a while before we can remove them.

**Comment by hadley** [comment]
I've spend a few minutes exploring this, I think we can get rid of the underscore functions relatively easily
